name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update README
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=ltseverydayyou&show_icons=true&theme=dark"
          curl -o languages.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=ltseverydayyou&layout=compact&theme=dark"

          cat <<EOL > README.md
          # Hello! I'm ltseverydayyou

          I script stuff and smthing.

          ## GitHub Stats

          ![Your GitHub Stats](stats.svg)

          ## Top Languages

          ![Top Languages](languages.svg)

          ## Repositories

          ### [uuuuuuu](https://github.com/ltseverydayyou/uuuuuuu)
          - **Stars:** $(curl -s "https://api.github.com/repos/ltseverydayyou/uuuuuuu" | jq '.stargazers_count')
          - **Forks:** $(curl -s "https://api.github.com/repos/ltseverydayyou/uuuuuuu" | jq '.forks_count')
          - **Last Commit:** $(curl -s "https://api.github.com/repos/ltseverydayyou/uuuuuuu/commits?per_page=1" | jq -r '.[0].commit.message') on $(curl -s "https://api.github.com/repos/ltseverydayyou/uuuuuuu/commits?per_page=1" | jq -r '.[0].commit.author.date')

          ### [Nameless-Admin](https://github.com/ltseverydayyou/Nameless-Admin)
          - **Stars:** $(curl -s "https://api.github.com/repos/ltseverydayyou/Nameless-Admin" | jq '.stargazers_count')
          - **Forks:** $(curl -s "https://api.github.com/repos/ltseverydayyou/Nameless-Admin" | jq '.forks_count')
          - **Last Commit:** $(curl -s "https://api.github.com/repos/ltseverydayyou/Nameless-Admin/commits?per_page=1" | jq -r '.[0].commit.message') on $(curl -s "https://api.github.com/repos/ltseverydayyou/Nameless-Admin/commits?per_page=1" | jq -r '.[0].commit.author.date')

          Feel free to explore my repositories and reach out if you have any questions!
          EOL

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with latest stats"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ltseverydayyou/ltseverydayyou.git
